sudo: required
services:
    - docker

before_install:
    - docker build -t malfoy27/docker-react -f Dockerfile.dev .

script:
    - docker run malfoy27/docker-react npm run test -- --coverage

deploy:
    provider: elasticbeanstalk
    region: "us-west-2"
    app: "docker"
    environment: "Docker-env"
    bucket_name: ""
    bucket_path: "docker" #same as app name
    on:
        branch: master
        